openapi: 3.0.3
info:
  title: VRChat API Documentation
  version: 1.1.2
  contact:
    name: Unofficial VRChat API Documentation Project
    url: 'https://github.com/VRChatAPI'
    email: me@ruby.js.org
  termsOfService: 'https://vrchat.com/legal/'
  license:
    url: 'https://github.com/vrchatapi/specification/blob/master/LICENSE'
    name: The MIT License (MIT)
  description: "![VRChat API Banner](https://vrchatapi.github.io/assets/img/api_banner_1500x400.png)\n\n# Welcome to the VRChat API\n\nBefore we begin, we would like to state this is a **COMMUNITY DRIVEN PROJECT**.\nThis means that everything you read on here was written by the community itself and is **not** officially supported by VRChat.\nThe documentation is provided \"AS IS\", and any action you take towards VRChat is completely your own responsibility.\n\nThe documentation and additional libraries SHALL ONLY be used for applications interacting with VRChat's API in accordance\nwith their [Terms of Service](https://github.com/VRChatAPI), and MUST NOT be used for modifying the client, \"avatar ripping\", or other illegal activities.\nMalicious usage or spamming the API may result in account termination.\nCertain parts of the API are also more sensitive than others, for example moderation, so please tread extra carefully and read the warnings when present.\n\n![Tupper Policy on API](https://i.imgur.com/yLlW7Ok.png)\n\nFinally, use of the API using applications other than the approved methods (website, VRChat application, Unity SDK) is not officially supported.\nVRChat provides no guarantee or support for external applications using the API. Access to API endpoints may break **at any time, without notice**.\nTherefore, please **do not ping** VRChat Staff in the VRChat Discord if you are having API problems, as they do not provide API support.\nWe will make a best effort in keeping this documentation and associated language libraries up to date, but things might be outdated or missing.\nIf you find that something is no longer valid, please contact us on Discord or [create an issue](https://github.com/vrchatapi/specification/issues) and tell us so we can fix it.\n\n# Getting Started\n\nThe VRChat API can be used to programmatically retrieve or update information regarding your profile, friends, avatars, worlds and more.\nThe API consists of two parts, \"Photon\" which is only used in-game, and the \"Web API\" which is used by both the game and the website.\nThis documentation focuses only on the Web API.\n\nThe API is designed around the REST ideology, providing semi-simple and usually predictable URIs to access and modify objects.\nRequests support standard HTTP methods like GET, PUT, POST, and DELETE and standard status codes.\nResponse bodies are always UTF-8 encoded JSON objects, unless explicitly documented otherwise.\n\n<div class=\"callout callout-error\">\n  <strong>\U0001F6D1 Warning! Do not touch Photon!</strong><br>\n  Photon is only used by the in-game client and should <b>not</b> be touched. Doing so may result in permanent account termination.\n</div>\n\n<div class=\"callout callout-info\">\n  <strong>ℹ️ API Key and Authentication</strong><br>\n  The API Key has always been the same and is currently <code>JlE5Jldo5Jibnk5O5hTx6XVqsJu4WJ26</code>.\n  Read <a href=\"#tag--authentication\">Authentication</a> for how to log in.\n</div>\n\n# Using the API\n\nFor simply exploring what the API can do it is strongly recommended to download [Insomnia](https://insomnia.rest/download), a free and open-source\nAPI client that's great for sending requests to the API in an orderly fashion.\nInsomnia allows you to send data in the format that's required for VRChat's API.\nIt is also possible to try out the API in your browser, by first logging in at [vrchat.com/home](https://vrchat.com/home/) and then going to\n[vrchat.com/api/1/auth/user](https://vrchat.com/api/1/auth/user), but the information will be much harder to work with.\n\nFor more permanent operation such as software development it is instead recommended to use one of the existing language SDKs.\nThis community project maintains API libraries in several languages, which allows you to interact with the API with simple function calls\nrather than having to implement the HTTP protocol yourself. Most of these libraries are automatically generated from the API specification,\nsometimes with additional helpful wrapper code to make usage easier. This allows them to be almost automatically updated and expanded upon\nas soon as a new feature is introduced in the specification itself. The libraries can be found on [GitHub](https://github.com/vrchatapi) or following:\n\n* [NodeJS (JavaScript)](https://www.npmjs.com/package/vrchat)\n* [Dart](https://pub.dev/packages/vrchat_dart)\n* [Rust](https://crates.io/crates/vrchatapi)\n* [C#](https://github.com/vrchatapi/vrchatapi-csharp)\n* [Python](https://github.com/vrchatapi/VRChatPython)\n\n# Pagination\n\nMost endpoints enforce pagination, meaning they will only return 10 entries by default, and never more than 100.<br>\nUsing both the limit and offset parameters allows you to easily paginate through a large number of objects.\n\n| Query Parameter | Type | Description |\n| ----------|--|------- |\n| `limit` | integer  | The number of objects to return. This value often defaults to 10. Highest limit is always 100.|\n| `offset` | integer  | A zero-based offset from the default object sorting.|\n\nIf a request returns fewer objects than the `limit` parameter, there are no more items available to return.\n\n# Contribution\n\nDo you want to get involved in the documentation effort? Do you want to help improve one of the language API libraries?\nThis project is an [OPEN Open Source Project](https://openopensource.org)! This means that individuals making significant and valuable contributions are given\ncommit-access to the project. It also means we are very open and welcoming of new people making contributions, unlike some more guarded open-source projects.\n\n[![Discord](https://img.shields.io/static/v1?label=vrchatapi&message=discord&color=blueviolet&style=for-the-badge)](https://discord.gg/qjZE9C9fkB)"
servers:
  - url: 'https://api.vrchat.cloud/api/1'
paths:
  /auth:
    $ref: ./components/paths/authentication.yaml#/paths/~1auth
  /logout:
    $ref: ./components/paths/authentication.yaml#/paths/~1logout
  /auth/user:
    $ref: ./components/paths/authentication.yaml#/paths/~1auth~1user
  /auth/twofactorauth/totp/verify:
    $ref: ./components/paths/authentication.yaml#/paths/~1auth~1twofactorauth~1totp~1verify
  /auth/twofactorauth/otp/verify:
    $ref: ./components/paths/authentication.yaml#/paths/~1auth~1twofactorauth~1otp~1verify
  '/user/{userId}/delete':
    $ref: './components/paths/authentication.yaml#/paths/~1user~1{userId}~1delete'
  /users:
    $ref: './components/paths/users.yaml#/paths/~1users'
  '/users/{username}/name':
    $ref: './components/paths/users.yaml#/paths/~1users~1{username}~1name'
  '/users/{userId}':
    $ref: './components/paths/users.yaml#/paths/~1users~1{userId}'
  /users/active:
    $ref: './components/paths/users.yaml#/paths/~1users~1active'
  /health:
    $ref: ./components/paths/system.yaml#/paths/~1health
  /config:
    $ref: ./components/paths/system.yaml#/paths/~1config
  /visits:
    $ref: ./components/paths/system.yaml#/paths/~1visits
  /time:
    $ref: ./components/paths/system.yaml#/paths/~1time
  /auth/user/friends:
    $ref: ./components/paths/friends.yaml#/paths/~1auth~1user~1friends
  '/user/{userId}/friendStatus':
    $ref: ./components/paths/friends.yaml#/paths/~1user~1{userId}~1friendStatus
  '/user/{userId}/friendRequest':
    $ref: ./components/paths/friends.yaml#/paths/~1user~1{userId}~1friendRequest
  '/auth/user/friends/{userId}':
    $ref: ./components/paths/friends.yaml#/paths/~1auth~1user~1friends~1{userId}
  /auth/user/notifications:
    $ref: ./components/paths/notifications.yaml#/paths/~1auth~1user~1notifications
  '/auth/user/notifications/{notificationId}/see':
    $ref: ./components/paths/notifications.yaml#/paths/~1auth~1user~1notifications~1{notificationId}~1see
  '/auth/user/notifications/{notificationId}/hide':
    $ref: ./components/paths/notifications.yaml#/paths/~1auth~1user~1notifications~1{notificationId}~1hide
  '/auth/user/notifications/{notificationId}/accept':
    $ref: ./components/paths/notifications.yaml#/paths/~1auth~1user~1notifications~1{notificationId}~1accept
  /auth/user/notifications/clear:
    $ref: ./components/paths/notifications.yaml#/paths/~1auth~1user~1notifications~1clear
  /files:
    $ref: ./components/paths/files.yaml#/paths/~1files
  /file:
    $ref: ./components/paths/files.yaml#/paths/~1file
  '/file/{fileId}':
    $ref: ./components/paths/files.yaml#/paths/~1file~1{fileId}
  '/file/{fileId}/{versionId}':
    $ref: ./components/paths/files.yaml#/paths/~1file~1{fileId}~1{versionId}
  '/file/{fileId}/{versionId}/{fileType}/status':
    $ref: ./components/paths/files.yaml#/paths/~1file~1{fileId}~1{versionId}~1{fileType}~1status
  '/file/{fileId}/{versionId}/{fileType}/start':
    $ref: ./components/paths/files.yaml#/paths/~1file~1{fileId}~1{versionId}~1{fileType}~1start
  '/file/{fileId}/{versionId}/{fileType}/finish':
    $ref: ./components/paths/files.yaml#/paths/~1file~1{fileId}~1{versionId}~1{fileType}~1finish
  /worlds:
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds
  /worlds/active:
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1active
  /worlds/recent:
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1recent
  /worlds/favorites:
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1favorites
  '/worlds/{worldId}':
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1{worldId}
  '/worlds/{worldId}/{instanceId}':
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1{worldId}~1{instanceId}
  '/worlds/{worldId}/metadata':
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1{worldId}~1metadata
  '/worlds/{worldId}/publish':
    $ref: ./components/paths/worlds.yaml#/paths/~1worlds~1{worldId}~1publish
  /favorites:
    $ref: ./components/paths/favorites.yaml#/paths/~1favorites
  '/favorites/{favoriteId}':
    $ref: ./components/paths/favorites.yaml#/paths/~1favorites~1{favoriteId}
  /favorite/groups:
    $ref: ./components/paths/favorites.yaml#/paths/~1favorite~1groups
  '/favorite/group/{favoriteGroupType}/{favoriteGroupName}/{userId}':
    $ref: ./components/paths/favorites.yaml#/paths/~1favorite~1group~1{favoriteGroupType}~1{favoriteGroupName}~1{userId}
  /avatars/favorites:
    $ref: ./components/paths/avatars.yaml#/paths/~1avatars~1favorites
  /avatars:
    $ref: ./components/paths/avatars.yaml#/paths/~1avatars
  '/avatars/{avatarId}':
    $ref: ./components/paths/avatars.yaml#/paths/~1avatars~1{avatarId}
  '/avatars/{avatarId}/select':
    $ref: ./components/paths/avatars.yaml#/paths/~1avatars~1{avatarId}~1select
  /auth/user/playermoderations:
    $ref: ./components/paths/playermoderation.yaml#/paths/~1auth~1user~1playermoderations
  /auth/user/unplayermoderate:
    $ref: ./components/paths/playermoderation.yaml#/paths/~1auth~1user~1unplayermoderate
  '/auth/user/playermoderations/{playerModerationId}':
    $ref: ./components/paths/playermoderation.yaml#/paths/~1auth~1user~1playermoderations~1{playerModerationId}
  /auth/permissions:
    $ref: ./components/paths/permissions.yaml#/paths/~1auth~1permissions
  /permissions:
    $ref: ./components/paths/permissions.yaml#/paths/~1permissions
  '/permissions/{permissionId}':
    $ref: './components/paths/permissions.yaml#/paths/~1permissions~1{permissionId}'
components:
  schemas: {}
  securitySchemes:
    apiKeyQuery:
      name: apiKey
      type: apiKey
      in: query
      description: API Key via Query
    apiKeyCookie:
      name: apiKey
      type: apiKey
      in: cookie
      description: API Key via Cookie
    authHeader:
      type: http
      scheme: basic
      description: Auth token via Header
    authCookie:
      name: auth
      type: apiKey
      in: cookie
      description: Auth Token via Cookie
    twoFactorAuthCookie:
      name: twoFactorAuth
      type: apiKey
      in: cookie
      description: 2FA device remembrance via Cookie
  responses:
  parameters:
    number:
      name: 'n'
      in: query
      required: false
      schema:
        type: integer
        maximum: 100
        minimum: 1
        default: 60
      description: The number of objects to return.
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
      description: A zero-based offset from the default object sorting from where search results start.
    sortOptions:
      name: sort
      in: query
      required: false
      schema:
        title: SortOptions
        type: string
        default: popularity
        enum:
          - popularity
          - heat
          - trust
          - shuffle
          - random
          - favorites
          - reportScore
          - reportCount
          - publicationDate
          - labsPublicationDate
          - created
          - _created_at
          - updated
          - _updated_at
          - order
          - relevance
          - magic
          - name
        example: popularity
        description: How to sort
    orderOptions:
      name: order
      in: query
      required: false
      schema:
        title: OrderOptions
        type: string
        default: descending
        enum:
          - ascending
          - descending
        example: descending
        description: Result ordering
    releaseStatus:
      name: releaseStatus
      in: query
      required: false
      schema:
        type: string
        default: hidden
        enum:
          - public
          - private
          - hidden
        example: hidden
      description: Filter by ReleaseStatus.
    offline:
      name: offline
      in: query
      required: false
      schema:
        type: boolean
      description: 'Returns *only* offline users if true, returns only online and active users if false'
    fileId:
      name: fileId
      in: path
      required: true
      schema:
        type: string
        example: file_00000000-0000-0000-0000-000000000000
        pattern: 'file_[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}'
    versionId:
      name: versionId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        example: 1
    fileType:
      name: fileType
      in: path
      required: true
      schema:
        type: string
        enum:
          - file
          - signature
          - delta
        example: file
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
    maxUnityVersion:
      name: maxUnityVersion
      in: query
      required: false
      schema:
        type: string
      description: The maximum Unity version supported by the asset.
    minUnityVersion:
      name: minUnityVersion
      in: query
      required: false
      schema:
        type: string
      description: The minimum Unity version supported by the asset.
    platform:
      name: platform
      in: query
      required: false
      schema:
        type: string
      description: The platform the asset supports.
    tag:
      name: tag
      in: query
      required: false
      schema:
        type: string
      description: Tags to include (comma-separated).
    notag:
      name: notag
      in: query
      required: false
      schema:
        type: string
      description: Tags to exclude (comma-separated).
    search:
      name: search
      in: query
      required: false
      schema:
        type: string
      description: Filters by world name.
    userIdQuery:
      name: userId
      in: query
      required: false
      schema:
        type: string
      description: Filter by author UserID
    featured:
      name: featured
      in: query
      required: false
      schema:
        type: string
      description: Filters on featured results.
    userIdAdmin:
      name: userId
      in: query
      required: false
      schema:
        type: string
      description: 'Target user to see information on, admin-only.'
    worldId:
      name: worldId
      in: path
      required: true
      schema:
        type: string
    instanceId:
      name: instanceId
      in: path
      required: true
      schema:
        type: string
    favoriteId:
      name: favoriteId
      in: path
      required: true
      schema:
        type: string
    favoriteGroupType:
      name: favoriteGroupType
      in: path
      required: true
      schema:
        type: string
        enum:
          - world
          - friend
          - avatar
      description: 'The type of group to fetch, must be a valid FavoriteType.'
    favoriteGroupName:
      name: favoriteGroupName
      in: path
      required: true
      schema:
        type: string
    avatarId:
      name: avatarId
      in: path
      required: true
      schema:
        type: string
tags:
  - name: authentication
  - name: avatars
  - name: favorites
  - name: files
  - name: friends
  - name: notifications
  - name: permissions
  - name: playermoderation
  - name: system
  - name: users
  - name: worlds
