title: APIConfigAnnouncement
deprecated: true
type: object
description: Public Announcement
properties:
  name:
    type: string
    description: Announcement name
    minLength: 1
  text:
    type: string
    description: Announcement text
    minLength: 1
required:
  - name
  - text
