title: APIConfigEvents
type: object
required:
  - distanceClose
  - distanceFactor
  - distanceFar
  - groupDistance
  - maximumBunchSize
  - notVisibleFactor
  - playerOrderBucketSize
  - playerOrderFactor
  - slowUpdateFactorThreshold
  - viewSegmentLength
properties:
  distanceClose:
    description: Unknown
    type: integer
  distanceFactor:
    description: Unknown
    type: integer
  distanceFar:
    description: Unknown
    type: integer
  groupDistance:
    description: Unknown
    type: integer
  maximumBunchSize:
    description: Unknown
    type: integer
  notVisibleFactor:
    description: Unknown
    type: integer
  playerOrderBucketSize:
    description: Unknown
    type: integer
  playerOrderFactor:
    description: Unknown
    type: integer
  slowUpdateFactorThreshold:
    description: Unknown
    type: integer
  viewSegmentLength:
    description: Unknown
    type: integer
