title: InstanceContentSettings
type: object
description: Types of dynamic user content permitted in an instance
properties:
  drones:
    type: boolean
    default: true
  emoji:
    type: boolean
    default: true
  pedestals:
    type: boolean
    default: true
  prints:
    type: boolean
    default: true
  props:
    type: boolean
    default: true
  stickers:
    type: boolean
    default: true
